version: "3.9"

services:
  redis-cluster:
    image: grokzen/redis-cluster
    ports:
      - 7000-7005:7000-7005
    environment:
      - IP=0.0.0.0

  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/conf/postgres.conf:/etc/postgresql/postgresql.conf
      - ./postgres/log:/var/log/postgresql
    environment:
      - POSTGRES_PASSWORD=!QAZ2wsx
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8081:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@ohdada.com
      - PGADMIN_DEFAULT_PASSWORD=!QAZ2wsx

  static-file-server:
    image: halverneus/static-file-server
    ports:
      - 8000:8080
    volumes:
      - ./static-file-server/streaming-206:/web

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306 
    environment:
      - MYSQL_ROOT_PASSWORD=!QAZ2wsx

  nats:
    image: nats:latest
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222

  elasticsearch:
    image: elasticsearch:7.17.7
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node